### ISSUE TITLE
Invalid expression type()

### ISSUE THREAD

**Issue by mikaoelitiana** [n0v1c3/vira#34]
I have just installed vira and configured some servers in `~/.config/vira/vira_servers.json` but when I run any vira command, I have an issue:

```
Erreur détectée en traitant function vira#_menu[63]..vira#_print_menu :
ligne    3 :
E15: Expression invalide : >type() == type([]))
E15: Expression invalide : (a:list->type() == type([]))
```

**Comment by n0v1c3** [comment]
This will become our top priority to look into. We are preparing the first true office release on the dev branch right now and will merge it with master as soon as we can repeat and correct the issue.

**Comment by mikaoelitiana** [comment]
Thanks @n0v1c3

**Comment by n0v1c3** [comment]
The readme will have a few changes to the layout of the config in the dev branch for new features.

I am currently using the yaml setup so check that out as well.

**Comment by n0v1c3** [comment]
I at least merged the current dev (V0.0.1) to the `master` branch.

@mikaoelitiana Python version needs to be 3 along with have jira added and Vim version comes up a bit for that error code just wanted to check with you what version you are using. If you could let us know `:version` would be appreciated.

**Comment by mikaoelitiana** [comment]
Here is my `:version` content: 

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototyp
es -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/ne
ovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compilé par brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

**Comment by n0v1c3** [comment]
I can currently recreate it. I switched from `vim` to `nvim` and I started to get the same error.

**Comment by n0v1c3** [comment]
VIRA-162: type function call modified for neovim

@mikaoelitiana this was able to make it work on my neovim please let me know how it works for you.

**Comment by mikaoelitiana** [comment]
Yes this fixed the issue and I now can see the servers. But now I am facing new issue: 

```
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vim' is not defined
```

Maybe I am missing a dependency?

**Comment by n0v1c3** [comment]
@mikaoelitiana Thank you for the update and feedback it is very appreciated.

I just want to confirm if this comes up with the servers or when one is selected?

First guess you can try: `pip install --user pynvim` **"Please Note Where I was Reading Says '--user' may not be possible"**

**Comment by n0v1c3** [comment]
FYI:
https://github.com/neovim/neovim/issues/10270

**Comment by mikaoelitiana** [comment]
@n0v1c3 to answer your first question, this happens when selecting on server. I will try installing this package

**Comment by mikaoelitiana** [comment]
I had to install it with `pip3` but it seems that I already have it : 

```
:!pip3 install --user pynvim
Requirement already satisfied: pynvim in /Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages (0.4.1)
Requirement already satisfied: greenlet in /Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages (from pynvim) (0.4.15)
Requirement already satisfied: msgpack>=0.5.0 in /Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages (from pynvim) (1.0.0)
```

**Comment by mikeboiko** [comment]
@mikaoelitiana, it seems neovim recently patched this issue:
https://github.com/neovim/pynvim/commit/2cbc13553b113386d23ef225344e61172763ee45
https://github.com/neovim/pynvim/pull/430

Users reported that neovim wasn't automatically importing the vim python module in the same manner as vim was.
Can you try manually running this command before connecting to a jira server:
`py3 ("import vim")`
If this works successfully, perhaps you just need to update neovim to the latest version. It worked for @n0v1c3 yesterday when running on the latest neovim from the arch linux pacman repository.

**Comment by mikeboiko** [comment]
@mikaoelitiana, I was able to re-create your problem on neovim.
I have found a temporary solution to the problem and want to confirm that it also works for you.
You should be able to connect to jira successfully if you first run `:checkhealth`
After this try running
```
:ViraServers
:ViraIssues
```
Once this is confirmed, we can drill down and find a proper solution for this issue.

**Comment by mikaoelitiana** [comment]
@mikeboiko I am already on latest stable vim 0.4.3, do you mean 0.5.0?

**Comment by mikeboiko** [comment]
@mikaoelitiana, yea that should be fine. I'm not 100% sure which version neovim included that patch in but I don't think your version is the problem.

**Comment by mikeboiko** [comment]
@mikaoelitiana, can you try the latest vira commit on the dev branch? I patched the issue.

**Comment by n0v1c3** [comment]
`master` merge from `dev`: `VIRA 0.0.3 - python3 import vim support for neovim`

@mikeboiko thanks for joining in. I looked at your modification on the `dev` branch and it did not hurt my ability to run. 

@mikaoelitiana I merged it into the `master` branch for easy updates and testing.

**Comment by n0v1c3** [comment]
@mikeboiko one other note. If you had a good way to recreate this issue add it to VIRA-162 comments for my upcoming new Story issue for a testing feature.

**Comment by mikeboiko** [comment]
> 
> 
> @mikeboiko one other note. If you had a good way to recreate this issue add it to VIRA-162 comments for my upcoming new Story issue for a testing feature.
> 
> Thanks

already done

**Comment by mikaoelitiana** [comment]
I no longer have the error on latest `dev` branch, what I have is some issues on the http request, it seems to be credentials on my end.

**Comment by n0v1c3** [comment]
@mikaoelitiana you may need to go to the website through the actual browser and login along with entering the confirmation that you are human. @mikeboiko was having similar issues and added the `"skip_cert_verify": true` to the `vira_servers` file and may be related.

We do have an issue already regarding the `pass` command being used regarding multi-line (pass or descriptions included) I currently needed to remove the website link I like to store in my `pass` to avoid that one. Also, try just using `password` instead of `password_cmd` at least for a test and then we can keep digging.

**Comment by mikaoelitiana** [comment]
@n0v1c3 that didn't help. I have tried `password` with "real" password and "api token" generated in my account but none worked. I wonder if this is linked to any special char used in my password?

**Comment by n0v1c3** [comment]
@mikaoelitiana I was about to ask if you had any special chars. It should have been covered but it is worth looking into.

**Comment by n0v1c3** [comment]
Did that get rid of it?

**Comment by n0v1c3** [comment]
@mikeboiko I believe it may have something to do with the cloud services and tokens. Below is the reported problem along with the first attempt coming for the api key. I believe we simply add another password type for key handling.

https://community.atlassian.com/t5/Jira-questions/How-to-authenticate-to-Jira-REST-API/qaq-p/814987

https://community.atlassian.com/t5/Jira-questions/How-to-use-API-token-for-REST-calls-in-Python/qaq-p/760940

**Comment by mikeboiko** [comment]
@n0v1c3, at a glance that sounds like a reasonable solution. Let's see what @mikaoelitiana's error message says first. It may be as simple as adding an API key login.

**Comment by n0v1c3** [comment]
@mikeboiko looks like when I changed our connect from an `auth` to a `basic_auth` it will allow the connection however, I currently do not see the issues. **No Errors**

**Comment by n0v1c3** [comment]
This looks like the website is using API3 and python appears to use API2 this may be another part of the problem.

**Comment by mikeboiko** [comment]
Yea if that's the case we can handle for that by having an option to change rest_api_version.
See https://jira.readthedocs.io/en/master/api.html#jira.JIRA

**Comment by n0v1c3** [comment]
Good day @mikeboiko nice find confirmed default is version 2 I will give that a try after some coffee this morning.

**Comment by n0v1c3** [comment]
I also sent you an invite to my new Jira online for is to test this.

**Comment by mikeboiko** [comment]
good plan! I accepted your invite yesterday. Check out the board.

**Comment by n0v1c3** [comment]
I guess I should. I never leave Vim though and, I can't see my issue yet.

**Comment by mikaoelitiana** [comment]
Unfortunately I don't directly see the http error, I have something like this: 
```
ligne   18 :
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mikaoelitiana/.config/nvim/plugged/vira/autoload/../python/Vira/vira_api.py", line 152, in connect
    timeout=5)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 462, in __init__
    user = self.session(auth)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 2446, in session
    r = self._session.post(url, data=json.dumps(authentication_data))
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/resilientsession.py", line 154, in post
    return self.__verb('POST', url, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/resilientsession.py", line 125, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 208, in handle_401
    self.init_session()
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 224, in init_session
    self.start_session()
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 238, in start_session
    self._get_session(self.__auth)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 2446, in session
    r = self._session.post(url, data=json.dumps(authentication_data))
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/resilientsession.py", line 154, in post
    return self.__verb('POST', url, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/resilientsession.py", line 125, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 208, in handle_401
    self.init_session()
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 224, in init_session
    self.start_session()
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 238, in start_session
    self._get_session(self.__auth)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 2446, in session
    r = self._session.post(url, data=json.dumps(authentication_data))
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/resilientsession.py", line 154, in post
    return self.__verb('POST', url, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/resilientsession.py", line 125, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 208, in handle_401
    self.init_session()
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 224, in init_session
    self.start_session()
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 238, in start_session
    self._get_session(self.__auth)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 2446, in session
    r = self._session.post(url, data=json.dumps(authentication_data))
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/resilientsession.py", line 154, in post
    return self.__verb('POST', url, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/jira/resilientsession.py", line 125, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "/Users/mikaoelitiana/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
```

**Comment by n0v1c3** [comment]
@mikaoelitiana thank you again. I was able to create that same error and it looks like the API has changed for their website. I think I know the core of this problem I am just looking for a solution to the API version.

I can get rid of the error you are seeing I am just focused on "show my issues" right now.

**Comment by n0v1c3** [comment]
I at least pushed the change that gets rid of the long wait and the error message. I will let you know when I can see my errors from an API3 server.

@mikeboiko I think I will start a new issue as VIRA-162 is fixed for the `nvim` and we found a new issue for Jira API versions.

**Comment by n0v1c3** [comment]
https://developer.atlassian.com/cloud/jira/platform/rest/v3/?utm_source=%2Fcloud%2Fjira%2Fplatform%2Frest%2F&utm_medium=302#api-rest-api-3-applicationrole-get

**Comment by n0v1c3** [comment]
```
➜  n0v1c3 python3 test.py
[
    {
        "defaultGroups": [
            "jira-software-users"
        ],
        "defined": true,
        "groups": [
            "jira-software-users",
            "atlassian-addons-admin",
            "system-administrators",
            "trusted-users-bec42b23-464f-4f63-b642-4eae20763503",
            "site-admins",
            "administrators"
        ],
        "hasUnlimitedSeats": false,
        "key": "jira-software",
        "name": "Jira Software",
        "numberOfSeats": 10,
        "platform": false,
        "remainingSeats": 8,
        "selectedByDefault": false,
        "userCount": 2,
        "userCountDescription": "users"
    }
]
```

**Comment by n0v1c3** [comment]
@mikeboiko this worked for me to pull an issues details.
```
import requests
from requests.auth import HTTPBasicAuth
import json

url = "https://n0v1c3.atlassian.net/rest/api/3/issue/TEST-1"

auth = HTTPBasicAuth("username@email", "AUTHKEY")

headers = {
   "Accept": "application/json"
}

response = requests.request(
   "GET",
   url,
   headers=headers,
   auth=auth
)

print(json.dumps(json.loads(response.text), sort_keys=True, indent=4, separators=(",", ": ")))

``` 
```
{
    "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
    "fields": {
        "aggregateprogress": {
            "progress": 0,
            "total": 0
        },
        "aggregatetimeestimate": null,
        "aggregatetimeoriginalestimate": null,
        "aggregatetimespent": null,
        "assignee": null,
        "attachment": [],
        "comment": {
            "comments": [
                {
                    "author": {
                        "accountId": "5ed95bbf5313220aa1132871",
                        "accountType": "atlassian",
                        "active": true,
                        "avatarUrls": {
                            "16x16": "https://secure.gravatar.com/avatar/f136ea7edac9728cfbf18c9f024a9072?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FTG-2.png",
                            "24x24": "https://secure.gravatar.com/avatar/f136ea7edac9728cfbf18c9f024a9072?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FTG-2.png",
                            "32x32": "https://secure.gravatar.com/avatar/f136ea7edac9728cfbf18c9f024a9072?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FTG-2.png",
                            "48x48": "https://secure.gravatar.com/avatar/f136ea7edac9728cfbf18c9f024a9072?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FTG-2.png"
                        },
                        "displayName": "Travis Gall",
                        "emailAddress": "n0v1c3@gmail.com",
                        "self": "https://n0v1c3.atlassian.net/rest/api/3/user?accountId=5ed95bbf5313220aa1132871",
                        "timeZone": "Etc/GMT"
                    },
                    "body": {
                        "content": [
                            {
                                "content": [
                                    {
                                        "text": "Comment test",
                                        "type": "text"
                                    }
                                ],
                                "type": "paragraph"
                            }
                        ],
                        "type": "doc",
                        "version": 1
                    },
                    "created": "2020-06-05T15:39:14.932+0000",
                    "id": "10000",
                    "jsdPublic": true,
                    "self": "https://n0v1c3.atlassian.net/rest/api/3/issue/10000/comment/10000",
                    "updateAuthor": {
                        "accountId": "5ed95bbf5313220aa1132871",
                        "accountType": "atlassian",
                        "active": true,
                        "avatarUrls": {
                            "16x16": "https://secure.gravatar.com/avatar/f136ea7edac9728cfbf18c9f024a9072?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FTG-2.png",
                            "24x24": "https://secure.gravatar.com/avatar/f136ea7edac9728cfbf18c9f024a9072?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FTG-2.png",
                            "32x32": "https://secure.gravatar.com/avatar/f136ea7edac9728cfbf18c9f024a9072?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FTG-2.png",
                            "48x48": "https://secure.gravatar.com/avatar/f136ea7edac9728cfbf18c9f024a9072?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FTG-2.png"
                        },
                        "displayName": "Travis Gall",
                        "emailAddress": "n0v1c3@gmail.com",
                        "self": "https://n0v1c3.atlassian.net/rest/api/3/user?accountId=5ed95bbf5313220aa1132871",
                        "timeZone": "Etc/GMT"
                    },
                    "updated": "2020-06-05T15:39:14.932+0000"
                }
            ],
            "maxResults": 1,
            "startAt": 0,
            "total": 1
        },
        "components": [],
        "created": "2020-06-04T21:05:25.581+0000",
        "creator": {
            "accountId": "5a5d22db76a09c4111f48b15",
            "accountType": "atlassian",
            "active": true,
            "avatarUrls": {
                "16x16": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "24x24": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "32x32": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "48x48": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png"
            },
            "displayName": "Mike Boiko",
            "self": "https://n0v1c3.atlassian.net/rest/api/3/user?accountId=5a5d22db76a09c4111f48b15",
            "timeZone": "America/Denver"
        },
        "customfield_10000": "{}",
        "customfield_10001": null,
        "customfield_10002": null,
        "customfield_10003": null,
        "customfield_10004": null,
        "customfield_10005": null,
        "customfield_10006": null,
        "customfield_10007": null,
        "customfield_10008": null,
        "customfield_10009": null,
        "customfield_10010": null,
        "customfield_10014": null,
        "customfield_10015": null,
        "customfield_10016": null,
        "customfield_10017": null,
        "customfield_10018": {
            "hasEpicLinkFieldDependency": false,
            "nonEditableReason": {
                "message": "The Parent Link is only available to Jira Premium users.",
                "reason": "PLUGIN_LICENSE_ERROR"
            },
            "showField": false
        },
        "customfield_10019": "0|hzzzzz:",
        "customfield_10020": null,
        "customfield_10021": null,
        "customfield_10022": null,
        "customfield_10023": null,
        "customfield_10024": "2020-06-05T15:39:14.932+0000",
        "customfield_10025": "10000_*:*_1_*:*_5106_*|*_10002_*:*_1_*:*_0",
        "description": {
            "content": [
                {
                    "content": [
                        {
                            "text": "Description test",
                            "type": "text"
                        }
                    ],
                    "type": "paragraph"
                }
            ],
            "type": "doc",
            "version": 1
        },
        "duedate": null,
        "environment": null,
        "fixVersions": [],
        "issuelinks": [],
        "issuetype": {
            "avatarId": 10318,
            "description": "Tasks track small, distinct pieces of work.",
            "entityId": "cdb27d3d-e41c-46b8-857a-f03f71b12776",
            "iconUrl": "https://n0v1c3.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype",
            "id": "10001",
            "name": "Task",
            "self": "https://n0v1c3.atlassian.net/rest/api/3/issuetype/10001",
            "subtask": false
        },
        "labels": [],
        "lastViewed": "2020-06-05T15:38:55.954+0000",
        "priority": {
            "iconUrl": "https://n0v1c3.atlassian.net/images/icons/priorities/medium.svg",
            "id": "3",
            "name": "Medium",
            "self": "https://n0v1c3.atlassian.net/rest/api/3/priority/3"
        },
        "progress": {
            "progress": 0,
            "total": 0
        },
        "project": {
            "avatarUrls": {
                "16x16": "https://n0v1c3.atlassian.net/secure/projectavatar?size=xsmall&s=xsmall&pid=10000&avatarId=10407",
                "24x24": "https://n0v1c3.atlassian.net/secure/projectavatar?size=small&s=small&pid=10000&avatarId=10407",
                "32x32": "https://n0v1c3.atlassian.net/secure/projectavatar?size=medium&s=medium&pid=10000&avatarId=10407",
                "48x48": "https://n0v1c3.atlassian.net/secure/projectavatar?pid=10000&avatarId=10407"
            },
            "id": "10000",
            "key": "TEST",
            "name": "Test",
            "projectTypeKey": "software",
            "self": "https://n0v1c3.atlassian.net/rest/api/3/project/10000",
            "simplified": true
        },
        "reporter": {
            "accountId": "5a5d22db76a09c4111f48b15",
            "accountType": "atlassian",
            "active": true,
            "avatarUrls": {
                "16x16": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "24x24": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "32x32": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "48x48": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png"
            },
            "displayName": "Mike Boiko",
            "self": "https://n0v1c3.atlassian.net/rest/api/3/user?accountId=5a5d22db76a09c4111f48b15",
            "timeZone": "America/Denver"
        },
        "resolution": {
            "description": "Work has been completed on this issue.",
            "id": "10000",
            "name": "Done",
            "self": "https://n0v1c3.atlassian.net/rest/api/3/resolution/10000"
        },
        "resolutiondate": "2020-06-04T21:05:30.653+0000",
        "security": null,
        "status": {
            "description": "",
            "iconUrl": "https://n0v1c3.atlassian.net/",
            "id": "10002",
            "name": "Done",
            "self": "https://n0v1c3.atlassian.net/rest/api/3/status/10002",
            "statusCategory": {
                "colorName": "green",
                "id": 3,
                "key": "done",
                "name": "Done",
                "self": "https://n0v1c3.atlassian.net/rest/api/3/statuscategory/3"
            }
        },
        "statuscategorychangedate": "2020-06-04T21:05:30.667+0000",
        "subtasks": [],
        "summary": "Join the dark side (cloud)",
        "timeestimate": null,
        "timeoriginalestimate": null,
        "timespent": null,
        "timetracking": {},
        "updated": "2020-06-05T15:39:14.932+0000",
        "versions": [],
        "votes": {
            "hasVoted": false,
            "self": "https://n0v1c3.atlassian.net/rest/api/3/issue/TEST-1/votes",
            "votes": 0
        },
        "watches": {
            "isWatching": true,
            "self": "https://n0v1c3.atlassian.net/rest/api/3/issue/TEST-1/watchers",
            "watchCount": 2
        },
        "worklog": {
            "maxResults": 20,
            "startAt": 0,
            "total": 0,
            "worklogs": []
        },
        "workratio": -1
    },
    "id": "10000",
    "key": "TEST-1",
    "self": "https://n0v1c3.atlassian.net/rest/api/3/issue/10000"
}
```

**Comment by mikeboiko** [comment]
@n0v1c3, nice sounds like you're getting close to implementing the version 3 api

**Comment by n0v1c3** [comment]
Extra note. I was able to connect to our private servers however we will need to add a API2 vs API3 check.
```
url = "https://jira.myprivateserver.ca/rest/api/2/issue/VIRA-1"
```
notice the `2` vs the `3`

**Comment by n0v1c3** [comment]
If I can make the connection work with the `Jira` `python` class and functions would be best. However, I have the link for all `GET` that should be able to replace it.

**Comment by n0v1c3** [comment]
I can now read data but I cannot write it yet.

**Comment by n0v1c3** [comment]
I can now comment, set status are working I still need to fix create an issue.

**Comment by n0v1c3** [comment]
@mikaoelitiana and @mikeboiko I have released VIRA 0.0.5 and it should make it work.

@mikeboiko FYI load API3 and remove the users filter for the comments was needed to make it work. I will create a new issue regarding the users.

**Comment by mikaoelitiana** [comment]
@n0v1c3 this is it!! Now it's all good!!

**Comment by n0v1c3** [comment]
@mikaoelitiana I am very glad to hear that and see that this issue is closed. I am looking forward to you giving it a real test and please send me any ideas you have to make it a better vim tool.

You made me actually need to go to my websites for this one and I almost had forgotten what they looked like. Thanks!

**Comment by mikeboiko** [comment]
good work @n0v1c3!
